### ISSUE TITLE
Can't compile a proper Syncplay.exe

### ISSUE THREAD

**Issue by wiiaboo** [Uriziel/syncplay#51]
Trying to compile 'areYouReady' branch to try the new features, but can't seem to be able to run Syncplay.exe. syncplayClient.py runs fine.
Using Python 2.7 Win32.

Output of `pip2 freeze`: https://gist.github.com/6e0db74ada4650542e52
Output of `python buildPy2exe.py`: https://gist.github.com/4f6c467d6fe9c6bbb450

syncplay.log:
```
Traceback (most recent call last):
  File "syncplayClient.py", line 19, in <module>
  File "syncplay\clientManager.pyo", line 7, in run
  File "syncplay\ui\ConfigurationGetter.pyo", line 387, in getConfiguration
  File "syncplay\vendor\qt4reactor.pyo", line 41, in <module>
ImportError: No module named zope.interface
```

From the official installer file list, I noticed I'm missing two .pyd, "zope.interface._zope_interface_coptimizations.pyd" and "twisted.python._initgroups.pyd".

**Comment by Uriziel** [comment]
http://superuser.com/questions/124437/how-to-install-zope-on-windows

**Comment by wiiaboo** [comment]
That tells me nothing.
I do have both twisted and zope.interface installed as you can see from pip freeze.

**Comment by Uriziel** [comment]
Zope's egg doesn't create __init__.py in one of it's folders.

I was pretty sure the previous link would contain that info, but it didn't, my bad.

Following this link: http://stackoverflow.com/a/11632115/1891329
`Specifically, add an empty __init__.py file to the PYTHONDIR/Lib/site-packages/zope directory.`

**Comment by wiiaboo** [comment]
Awesome, that fixed it. Thanks.

**Comment by Et0h** [comment]
I've now added a note about this issue to the top of the file (https://github.com/Uriziel/syncplay/commit/3e6316e960f735150110e9ae2a3ab5dabedbaf60) and released an official installer with the areYouReady changes (and some bugfixes) as Syncplay 1.3.0 Beta 2. It'd be good to hear what your thoughts are on the new features (and if you find any bugs).

**Comment by wiiaboo** [comment]
Would be cool if "Autoplay when everyone is ready" saved its state. No bugs so far.

**Comment by Et0h** [comment]
Do you mean save state when you close and re-open Syncplay, or are you talking about it unchecking when someone leaves (to prevent clashes with the "Pause on leave" feature)?

It is already the case that if you press play when you are ready or everyone else is ready it will unpause, and otherwise it will just set you to ready (so you press play twice to unpause if others aren't ready), so people can just press play as a simple "unpause when everyone is ready" feature.

**Comment by wiiaboo** [comment]
I mean when closing and re-opening Syncplay. At least in my installation it doesn't remember that setting. I didn't remove configurations when upgrading.

**Comment by Et0h** [comment]
If you're talking about the checked/unchecked state of the button (rather than whether it is visible) then it isn't currently designed to keep that state. I can ask around to see what people think about it being persistent, although it would be forgotten if someone left a room in any case (to avoid conflict with the 'unpause when user leaves' feature). Long-term persistence could be confusing if it kept its state between different viewing sessions. If everyone is on then people should just press 'play' to show they are ready, and in that case if everyone is ready it will unpause (which is especially useful where people have their media windows full-screened on a single-monitor system, as then they don't have to switch from Syncplay).

**Comment by Et0h** [comment]
wiiaboo: Things have moved over to the main branch now. I've had a go add persistent auto-play, and coupled it with a minimum number of people requirement. Please let me know what you think / if it works.

**Comment by wiiaboo** [comment]
Ok, I'll try. I've seen a couple of bugs, but they're kinda hard to
describe and reproduce. Kinda hard without a second pc. I'll set up a vm.

**Comment by wiiaboo** [comment]
Works fine so far. No bugs whatsoever.
